name: Latest Medium Post
on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
jobs:
  update-readme-with-stack-overflow:
    name: Updated readme with the latest Medium post
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "MEDIUM"
          commit_message: "Updated readme with the latest Medium post"
          feed_list: "https://medium.com/feed/@jlopezlira"
